### ISSUE TITLE
General issues regarding pokemon locations and habitats

### ISSUE THREAD

**Issue by Bara1234** [RavenDS/dex-editor#4] opened 2024-04-03 16:17 UTC
The game is heartgold and i used the content on the dspre folder

After i started to change some mons and add some on their respectives routes it began to display incorrect in their new dex locations

I didn't change anything in the matrix

I also already have a save so i don't know if this affects how they are displayed in the changed dex

![image](https://github.com/RavenDS/dex-editor/assets/74211560/8dc973b6-7f2c-4c5c-8cb8-2c0a3b711dc6)

Some of the mons also started to show where they are in the kanto dex even though i didn't get it yet

![image](https://github.com/RavenDS/dex-editor/assets/74211560/8226dd4a-be04-4c9f-bb3a-a9ca2bd1ee30)

Some of the indoors change and the pokemons that can only be get in caves and such doesn't seem to be affected

![image](https://github.com/RavenDS/dex-editor/assets/74211560/8a81a042-56e0-427b-ba83-920171f3d3a2)

![image](https://github.com/RavenDS/dex-editor/assets/74211560/aec5aa08-3a00-4ce7-9ec2-745144a36631)

**Comment by RavenDS** [comment] 2024-04-04 08:23
Thanks for reporting, before i look into this i have to ask a few questions:

Which version of the Dex Editor are you using? Supposedly, versions before [v1.4](https://github.com/RavenDS/dex-editor/releases/tag/v1.4) had issues with habitats

Do you mean an actual game save or a save-state? 
Save-states are known to mess up how edited data is displayed.
If it's an actual game save, and you've only seen/caught a bunch of mons (not having an entire dex), then it can also interfere with how data is displayed, especially if you edited the dex order after saving. 

I'd suggest **using a 100% save with full dex when making dex edits to your rom**, order or habitat-related.

Please try the above first, and if this occurs again, please provide the following depending on the scenario:

If you edited a mon and its data isn't being displayed correctly
- Screenshot of the data from the Dex Editor
- Screenshot(s) of its dex entry (habitat)


If your edits interfered with another mon unexpectedly
- Screenshot of your edited data from the Dex Editor
- Screenshot of the other mon data from the Dex Editor
- Screenshot(s) of your edited mon dex entry
- Screenshot(s) of the other mon dex entry

**Comment by Bara1234** [comment] 2024-04-04 21:14
I have installed the latest version avaible, i also didn't use a save state nor a 100% save. 

I will try to get a full save on the game and see if it works (i made tons of changes in the rom so idk if it's gonna work)

**Comment by Bara1234** [comment] 2024-04-04 23:56
I tried a clean rom and worked fine, i didn't test a lot but i got the idea, what should i do to fix it on my changed rom?

**Comment by Bara1234** [comment] 2024-04-05 02:05
> I tried a clean rom and worked fine, i didn't test a lot but i got the idea, what should i do to fix it on my changed rom?

the full save on the changed rom didn't fix anything

**Comment by RavenDS** [comment] 2024-04-05 06:03
> I tried a clean rom and worked fine, i didn't test a lot but i got the idea, what should i do to fix it on my changed rom?

I cannot assist with fixing the old ROM, as i still don't know the source of the problem. I would need much more details on which mons you edited in order to establish correlations with the end result.

In order to transfer "clean" edited data to the "old" ROM, here's what you can do:
- Duplicate RavenDexEditor.exe in **another folder (very important, must be a different location)**
- Open your **"old" ROM** in a 1st instance of RavenDexEditor, let it unpack etc
- Using the duplicated .exe, open your new **"clean" ROM** in a 2nd instance of RavenDexEditor, let it unpack etc
- Open /RDETemp folder generated by the 2nd instance (clean), and copy **"encdata"** folder to /RDETemp folder generated by the 1st instance (old, replace all files)
- Close 2nd instance and click "Write to game folder" in 1st instance
- Now transfer **"/data/a/2/1/4"** from your "clean" DSPRE folder to your "old" DSPRE folder
_(you can also use Tinke to replace **/a/2/1/4** after exporting the ROM from DSPRE)_

**Comment by Bara1234** [comment] 2024-04-05 21:03
Thanks for the help. I changed almost every pokemon so it would be hard to say which one could be making a mess in the game, i guess i'll just wait till i finish the game and then apply the changes on the dex afterwards

**Comment by RavenDS** [comment] 2024-05-07 20:37
Closing as i couldn't reproduce the issue

**Closed by RavenDS** 2024-05-07 20:37 UTC
